version: "3.0"

services:
  home-warehouse:
    container_name: home_warehouse_app
    build:
      context: ../../
      dockerfile: warehouse-api/dockerfile
    ports:
      - 8000:8000
    networks:
      - home_warehouse_be

  mongo:
    container_name: home_warehouse_db
    image: mongo:latest
    volumes:
      - home_warehouse_db:/data/db
    networks:
      - home_warehouse_be

networks:
  home_warehouse_be:

volumes:
  home_warehouse_db: