version: "3.0"

services:
  home-warehouse:
    container_name: home-warehouse
    image: tafeen/home-warehouse:latest
    hostname: home-warehouse
    ports:
      - 8000:8000
    networks:
      - home_warehouse_be

  home-warehouse-mongo:
    container_name: home-warehouse-mongo
    hostname: home-warehouse-mongo
    image: mongo:latest
    volumes:
      - home_warehouse_db:/data/db
    networks:
      - home_warehouse_be

networks:
  home_warehouse_be:

volumes:
  home_warehouse_db: