version: "3.0"

services:
  home-warehouse:
    container_name: home-warehouse
    build: 
      context: ../../
      dockerfile: home-warehouse-api/dockerfile
    hostname: home-warehouse
    ports:
      - 8000:8000
    networks:
      - home_warehouse_be

  mongo-home-warehouse:
    container_name: home-warehouse-db
    hostname: mongo-home-warehouse
    image: mongo:latest
    volumes:
      - home_warehouse_db:/data/db
    networks:
      - home_warehouse_be

networks:
  home_warehouse_be:

volumes:
  home_warehouse_db: