version: "3.0"
services:
  home-warehouse-api:
    container_name: home-warehouse-api
    restart: always
    build: ../
    hostname: home-warehouse-api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ${API_DIR}:/usr/src/app/home-warehouse-api/data
    links:
      - mongo-home-warehouse
  home-warehouse-ui:
    container_name: home-warehouse-ui
    restart: always
    build: ../../home-warehouse-ui
    ports:
      - ${APP_PORT}:80
    links:
      - home-warehouse-api
  mongo-home-warehouse:
    container_name: home-warehouse-db
    hostname: mongo-home-warehouse
    restart: always
    image: mongo
    volumes:
      - ${DB_DIR}:/data/db